baseurl = "https://eduardo-gamboa.github.io/hugosite-edu-gamboa/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "red"
  showMenuItems = 5
  fullWidthTheme = true
  centerTheme = true

[languages]
  [languages.en]
    title = "Terminal - By Eduardo Gamboa"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal - Eduardo Gamboa 9A"
      logoHomeLink = "#"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
